<a href="https://colab.research.google.com/github/HagerArafat/Transformer_Task/blob/main/Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn.functional as F
import math

def self_attention(input_sentence):
    """Compute self-attention for a given input sentence"""

    tokens = input_sentence.split()
    print(f"Tokens: {tokens}")

    embedding_dim = 4
    vocab_size = len(tokens)


    embeddings = torch.randn(len(tokens), embedding_dim)
    print(f"\nEmbeddings:\n{embeddings}")


    positions = torch.arange(len(tokens)).unsqueeze(1)
    position_enc = torch.zeros(len(tokens), embedding_dim)

    for pos in range(len(tokens)):
        for i in range(0, embedding_dim, 2):
            position_enc[pos, i] = math.sin(pos / (10000 ** ((2 * i)/embedding_dim)))
            if i+1 < embedding_dim:
                position_enc[pos, i+1] = math.cos(pos / (10000 ** ((2 * (i+1))/embedding_dim)))

    print(f"\nPE:\n{position_enc}")

    X = embeddings + position_enc
    print(f"\nInput with PE (X):\n{X}")


    d_k = embedding_dim
    W_Q = torch.randn(embedding_dim, embedding_dim)
    W_K = torch.randn(embedding_dim, embedding_dim)
    W_V = torch.randn(embedding_dim, embedding_dim)

    print(f"\nWeight Matrices:")
    print(f"WQ:\n{W_Q}")
    print(f"WK:\n{W_K}")
    print(f"WV:\n{W_V}")


    Q = torch.matmul(X, W_Q)
    K = torch.matmul(X, W_K)
    V = torch.matmul(X, W_V)

    print(f"\n (Q):\n{Q}")
    print(f"(K):\n{K}")
    print(f"(V):\n{V}")


    attention_scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(d_k)
    print(f"\nRaw Attention Scores:\n{attention_scores}")


    attention_weights = F.softmax(attention_scores, dim=-1)
    print(f"\nAttention Weights (after softmax):\n{attention_weights}")


    output = torch.matmul(attention_weights, V)
    print(f"\nOutput:\n{output}")

    return output, attention_weights


input_sentence = "What are the symptoms of diabetes"
output, attn_weights = self_attention(input_sentence)

Tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes']

Embeddings:
tensor([[ 0.4744, -0.5460, -0.8796, -0.8389],
        [-0.7847, -0.3881, -0.9419,  1.4942],
        [-2.2813, -1.0201, -0.2815,  0.4560],
        [-0.7261, -1.3515,  0.5665,  0.6561],
        [ 0.4203, -0.6492, -1.1377,  0.4314],
        [ 0.5649, -2.6623,  0.7305,  0.7320]])

PE:
tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  9.9995e-01,  1.0000e-04,  1.0000e+00],
        [ 9.0930e-01,  9.9980e-01,  2.0000e-04,  1.0000e+00],
        [ 1.4112e-01,  9.9955e-01,  3.0000e-04,  1.0000e+00],
        [-7.5680e-01,  9.9920e-01,  4.0000e-04,  1.0000e+00],
        [-9.5892e-01,  9.9875e-01,  5.0000e-04,  1.0000e+00]])

Input with PE (X):
tensor([[ 0.4744,  0.4540, -0.8796,  0.1611],
        [ 0.0568,  0.6118, -0.9418,  2.4942],
        [-1.3720, -0.0203, -0.2813,  1.4560],
        [-0.5850, -0.3519,  0.5668,  1.6561],
        [-0.3365,  0.3500, -1.1373,  1.4314],
        [-0.3940, -1.