<a href="https://colab.research.google.com/github/HagerArafat/Transformer_Task/blob/main/Transformer_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn.functional as F
import math

def self_attention(input_sentence):
    """Compute self-attention for a given input sentence"""

    tokens = input_sentence.split()
    print(f"Tokens: {tokens}")

    embedding_dim = 4
    vocab_size = len(tokens)


    embeddings = torch.randn(len(tokens), embedding_dim)
    print(f"\nEmbeddings:\n{embeddings}")


    positions = torch.arange(len(tokens)).unsqueeze(1)
    position_enc = torch.zeros(len(tokens), embedding_dim)

    for pos in range(len(tokens)):
        for i in range(0, embedding_dim, 2):
            position_enc[pos, i] = math.sin(pos / (10000 ** ((2 * i)/embedding_dim)))
            if i+1 < embedding_dim:
                position_enc[pos, i+1] = math.cos(pos / (10000 ** ((2 * (i+1))/embedding_dim)))

    print(f"\nPositional Encodings:\n{position_enc}")

    X = embeddings + position_enc
    print(f"\nInput with Positional Encoding (X):\n{X}")


    d_k = embedding_dim
    W_Q = torch.randn(embedding_dim, embedding_dim)
    W_K = torch.randn(embedding_dim, embedding_dim)
    W_V = torch.randn(embedding_dim, embedding_dim)

    print(f"\nWeight Matrices:")
    print(f"W_Q:\n{W_Q}")
    print(f"W_K:\n{W_K}")
    print(f"W_V:\n{W_V}")


    Q = torch.matmul(X, W_Q)
    K = torch.matmul(X, W_K)
    V = torch.matmul(X, W_V)

    print(f"\nQuery Matrix (Q):\n{Q}")
    print(f"Key Matrix (K):\n{K}")
    print(f"Value Matrix (V):\n{V}")


    attention_scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(d_k)
    print(f"\nRaw Attention Scores:\n{attention_scores}")


    attention_weights = F.softmax(attention_scores, dim=-1)
    print(f"\nAttention Weights (after softmax):\n{attention_weights}")


    output = torch.matmul(attention_weights, V)
    print(f"\nOutput:\n{output}")

    return output, attention_weights


input_sentence = "What are the symptoms of diabetes"
output, attn_weights = self_attention(input_sentence)

Tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes']

Embeddings:
tensor([[-0.4747,  0.1867,  1.1207, -0.2936],
        [ 0.0089, -2.1953, -1.5260,  1.6199],
        [ 1.6481, -0.2639,  0.3676,  0.7481],
        [-0.4106,  0.0645,  0.7197, -0.8752],
        [-0.1234, -1.4437, -1.3458,  0.0978],
        [-0.0047, -0.7403, -1.7534, -1.5819]])

Positional Encodings:
tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  9.9995e-01,  1.0000e-04,  1.0000e+00],
        [ 9.0930e-01,  9.9980e-01,  2.0000e-04,  1.0000e+00],
        [ 1.4112e-01,  9.9955e-01,  3.0000e-04,  1.0000e+00],
        [-7.5680e-01,  9.9920e-01,  4.0000e-04,  1.0000e+00],
        [-9.5892e-01,  9.9875e-01,  5.0000e-04,  1.0000e+00]])

Input with Positional Encoding (X):
tensor([[-0.4747,  1.1867,  1.1207,  0.7064],
        [ 0.8503, -1.1954, -1.5259,  2.6199],
        [ 2.5574,  0.7359,  0.3678,  1.7481],
        [-0.2694,  1.0640,  0.7200,  0.1248],
        [-0.8802, -0.4445, -1.34